reset;
model nfl.mod;
data nfl.dat;
option solver cplex;
solve;

if solve_result = "solved" then {
  #Ara escribim en el fitxer els resultats
  printf "%d %d %d\n", n, r, s > ampl_result.out;
  for {i in 1..(n-1)} {
    for {j in (i+1)..n} {
      for {k in 1..kmax} {
        printf "%d %d %d %d\n", i, j, k, x[i,j,k] > ampl_result.out;
      }
    }
  }
}

if solve_result = "infeasible" then {
  print "No es possible programar el calendari sense descansos."
}
